apiVersion: apps/v1
kind: ReplicaSet
metadata:
  name: express-rc
  labels:
    name: express-rc
spec:
  # modify replicas according to your case
  replicas: 3
  selector:
    matchLabels:
      app: express-app
  template:
    metadata:
      labels:
        app: express-app
    spec:
      containers:
      - name: express
        image: public.ecr.aws/b7x8p9h1/cloudnativetutorial:latest
